USE master
GO

DROP DATABASE IF EXISTS EMS
GO

CREATE DATABASE EMS
ON
(
	NAME= EMS,
	FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MAHMUDSABUJ\MSSQL\DATA\EMS.mdf',
	SIZE=10MB,
	MAXSIZE=1GB,
	FILEGROWTH=10%
)
LOG ON
(
	NAME=EMS_log,
	FILENAME='C:\Program Files\Microsoft SQL Server\MSSQL15.MAHMUDSABUJ\MSSQL\DATA\EMS_log.ldf',
	SIZE=10MB,
	MAXSIZE=1GB,
	FILEGROWTH=10%
)
GO
USE EMS
GO
CREATE TABLE loginInfo
(
	userName VARCHAR(30),
	userPassword VARCHAR(10)
)
Go